### ISSUE TITLE
script 'som' should be adopted to 'Change namespace' commit 608c1dc 

### ISSUE THREAD

**Issue by gpummer** [SOM-st/TruffleSOM#16]
The script som missed the name change from 'som.vm.Universe' to 'truffles....' in line 121. This line should be changed to 'trufflesom.vm.Universe'.

Should I send a PR?

**Comment by smarr** [comment]
Hi, yeah, I kind of suspected we missed something.

A PR would be lovely.
Would also be great if we would actually test it, for instance like here:
https://github.com/smarr/SOMns/blob/release/build.xml#L288

**Comment by smarr** [comment]
This was fixed by #18.
